// <auto-generated />
namespace TravelProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ValidatedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidatedData));
        
        string IMigrationMetadata.Id
        {
            get { return "202501271217474_ValidatedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
